# Generated by Django 5.2.8 on 2025-12-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
